name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo xcodebuild -scheme SnapshotSafeView-Package\
            -project SnapshotSafeView.xcodeproj\
            -derivedDataPath ./buildData\
            -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=16.2"\
            build-for-testing

    - name: Tests
      run: |
        sudo xcodebuild test -scheme SnapshotSafeView-Package\
          -project SnapshotSafeView.xcodeproj\
          -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=16.2"\
          -derivedDataPath ./buildData\
          test-without-building

