name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: | 
          swift build -v \
            -Xswiftc "-sdk" \
            -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" \
            -Xswiftc "-target" \
            -Xswiftc "x86_64-apple-ios13.0-simulator"

      - name: Tests
        run: |
          sudo xcodebuild test -scheme SnapshotSafeView-Package\
            -project SnapshotSafeView.xcodeproj\
            -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=16.2"\
